server:
  port: 8080

spring:
    cloud:
        gateway:
            actuator:
              verbose:
                enabled: false
            routes:
            - id: api_route
              uri: http://httpbin.org
              predicates:
              - Host=*
              - Path=/get
              filters:
              - name: BearerTokenExchange
                args:
                  authServerBaseUrl: http://mockbin.org
                  tokenEndpointUrl: /echo
                  clientId: ${bearer-token-exchange.client-id}
                  clientSecret: ${bearer-token-exchange.client-secret}
                  issuerContainerType: ${bearer-token-exchange.issuer-container-type}
                  issuerContainerName: ${bearer-token-exchange.issuer-container-named}
                  audience: test
                  scope: test

management:
  server:
    port: 8081
  endpoint:
    gateway:
      enabled: true
  health:
    probes:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG
    lu.raiffeisen.gateway.apigateway.filters: DEBUG

bearer-token-exchange:
  auth-server-url: http://httpbin.org
  endpoint-uri: /post
  client-id: gateway
  client-secret: 214c1a56-f229-45e7-b932-021fe6f53922
  issuer-container-type: header
  issuer-container-named: X-TOKEN-SUBJECT-ISSUER
  audience: test
  scope: test

            