server:
  port: 8080

spring:
    cloud:
        gateway:
            actuator:
              verbose:
                enabled: false
            routes:
            - id: api_route
              uri: http://httpbin.org
              predicates:
              - Host=*
              - Path=/get
              filters:
              - name: BearerTokenExchange
#                args:
#                  scope: test
#                  authServerBaseUrl: http://httpbin2.org
#                  tokenEndpointUrl: /get
#                  clientId: ${bearer-token-exchange.client-id}
#                  clientSecret: ${bearer-token-exchange.client-secret}
#                  issuerContainerType: ${bearer-token-exchange.issuer-container-type}
#                  issuerContainerName: ${bearer-token-exchange.issuer-container-named}

management:
  endpoint:
    features:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.web.reactive: TRACE
    reactor.ipc.netty: TRACE
    reactor.netty: TRACE
    reactor.netty.http.client: TRACE

bearer-token-exchange:
  auth-server-url: http://httpbin.org
  endpoint-uri: /post
  client-id: gateway
  client-secret: 214c1a56-f229-45e7-b932-021fe6f53922
  issuer-container-type: header
  issuer-container-named: X-TOKEN-SUBJECT-ISSUER

            